# 注意: 在springboot2.0之前配置的servletpath为 servlet-path,  2.0之后配置的是servlet.path, 具体可参考ServerProperties.java源码
server:
  port: 9092
  servlet:
    path: /mq

# 配置文件中的坑, 如果key为no或者yes 那么spring在加载文件时会将它转成false或true 最后编程 product[true] / product[false]
product:
  id: product_10010

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    initialize: false
  jmx:
    enabled: false
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5

multipart:
  max-request-size: 20Mb
  max-file-size: 10Mb

logging:
  path: ./logs
  file: springboot-rabbitmq-01
  level:
    org:
      springframework: INFO
    com:
      fasterxml:
        jackson: INFO
      eugene:
        sumarry: DEBUG # level节点下的 com.eugene.sumarry  => 表示在这个包下面的DEBUG级别的log会打印出来

datasource:
  url: jdbc:mysql://127.0.0.1:3306/db_springboot?useUnicode=true&amp;characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: root
  password:

mybatis:
  config-location: classpath:mybatis-config.xml
  checkConfigLocation: true
  mapper-locations: classpath:mappers/*.xml

mq:
  env: local

basic:
  info:
    mq:
      exchange:
        name: ${mq.env}:basic:info:mq:directExchange
      routing:
        key:
          name: ${mq.env}:basic:info:mq:routing:key
      queue:
        name: ${mq.env}:basic:info:mq:queue
    simpleMq:
      queue:
        name: ${mq.env}:simple:queue
      exchange:
        name: ${mq.env}:simple:topicExchange
      routing:
        key:
          name: ${mq.env}:simple:routing:key
