# 注意: 在springboot2.0之前配置的servletpath为 servlet-path,  2.0之后配置的是servlet.path, 具体可参考ServerProperties.java源码
server:
  port: 9092
  servlet:
    path: /mq

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    initialize: false
  jmx:
    enabled: false
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 50

multipart:
  max-request-size: 20Mb
  max-file-size: 10Mb

logging:
  path: ./logs
  file: springboot-rabbitmq-01
  level:
    org:
      springframework: INFO
    com:
      fasterxml:
        jackson: INFO
      debug:
        steadyjack: DEBUG

mybatis:
  config-location: classpath:mybatis-config.xml
  checkConfigLocation: true
  mapper-locations: classpath:mappers/*.xml

mq:
  env:local

basic:
  info:
    mq:
      exchange:
        name: local:basic:info:mq:directExchange
      routing:
        key:
          name: local:basic:info:mq:routing:key
      queue:
        name: local:basic:info:mq:queue







